name: GERARDO GUERRA V.
favicon: null
layout_spectrum: 0.2446
typography_spectrum: 0.23281
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.20143817295320332
  lightness: 0.016940926434472203
  saturation: 0.43414803757332265
  rhythmicContrast: 0.6041455259546638
purpose: []
